name: Build and push Docker image 

on: 

  push: 

    branches: [ master ] 

  

jobs: 

  build-and-push: 

    runs-on: ubuntu-latest 

    steps: 

    - name: Checkout code 

      uses: actions/checkout@v2 

    - name: Login to Docker Hub 

      uses: docker/login-action@v1 

      with: 

        username: siddi108

        password: ${{ secrets.DOCKER_ACCESS_TOKEN }} 

    - name: Build and push Docker image 

      uses: docker/build-push-action@v2 

      with: 

        context: . 

        push: true 

        tags: siddi108/airplane:latest 

 
